//fr
var frSubs = {
  "nest": "Nest",
  "polygon": "Polygon",
  "getSpawnReport": "Get spawn report",
  "removeMap": "Remove from map",
  "exportPolygon": "Export Polygon",
  "exportVP": "Exporter points visibles",
  "countVP": "Compter points visibles",
  "copyClipboard": "Copy to clipboard",
  "poiViewer": "POI Viewer",
  "routeGenerator": "Route Generator",
  "hideGyms": "Hide gyms",
  "showGyms": "Show gyms",
  "hidePokestops": "Hide pokestops",
  "showPokestops": "Show pokestops",
  "hidePokestopRange": "Hide pokestop range",
  "showPokestopRange": "Show pokestop range",
  "hideSpawnpoints": "Hide spawnpoints",
  "showSpawnpoints": "Show spawnpoints",
  "showAllPOIS": "Show all POIs",
  "showUnknownPOIS": "Show unknown POIs only",
  "hideViewingCells": "Hide viewing cells",
  "showViewingCells": "Show viewing cells",
  "enableManualCircle": "Enable manual circle mode",
  "disableManualCircle": "Disable manual circle mode",
  "importOSM": "Importer les nests d'OSM",
  "importPolygon": "Importer polygon",
  "importInstance": "Importer instance",
  "clearRoute": "Clear route",
  "clearShapes": "Clear all shapes",
  "generateRoute": "Generate route",
  "generateOptimizedRoute": "Generate optimized route",
  "getOutput": "Get output",
  "openSettings": "Open settings",
  "delete": "Delete",
  "noData": "No data available.",
  "exEligible": " (ex-eligible)",
  "despawnTime": " Despawn time: ",
  "unknownDespawnTime": " unknown despawn time ",
  "count": "Count: ",
  "countTotal": "Count Total: ",
  "countGyms": "Count Gyms: ",
  "countStops": "Count Stops: ",
  "countSpawnpoints": "Count Spawnpoints: ",
  "spawnReport": "Spawn Report - ",
  "unnamed": "Unnamed",
  "at": "at",
  "skipped": " skipped, no data",
  "nestReport": "Nest Report - All Nests in View",
  "settings": "Paramètres",
  "routeOptAtt": "Route Optimization Attempts:",
  "tries": "Tries",
  "s2cells0": "S2cells (rouge) level:",
  "s2cells1": "S2cells (level 14, bleu)",
  "s2cells2": "S2cells (level 17, vert)",
  "circleRadius": "Radius du Circle:",
  "meters": "Mètres",
  "lastNestMigration": "Last Nest Migration:",
  "spawnReportLimit": "Spawn Report Limit:",
  "spawnReportLimitExp": "Pokemon (0 for unlimited)",
  "selectLanguage": "Choisi langue:",
  "chooseTileset": "Choisi Tileset:",
  "close": "Fermer",
  "output": "Output",
  "generatedRoute": "Generated route:",
  "getAllNests": "Get all nest reports",
  "countPoints": "Count points in Circles",
  "optimize": "Optimize!",
  "optimizeGyms": "Optimize for gyms",
  "optimizePokestops": "Optimize for pokestops",
  "optimizeSpawnpoints": "Optimize for all spawnpoints",
  "optimizeUnknownSpawnpoints": "Optimize for spawnpoints without TTH",
  "on": "On",
  "off": "Off",
  "optimizePiP": "Optimize points in polygons",
  "optimizePiNP": "Optimize points in nest polygons",
  "optimizePiC": "Optimize points in circles",
  "getOptimization": "Get Optimization",
  "copied": "Copié!",
  "selectInstance": "Select an instance:",
  "instanceColor": "Instance Color (hex):",
  "polygonDataType": "Polygon data type:",
  "coordinateList": "Coordinate list (latitude,longitude on each new line)",
  "geoJson": "GeoJSON",
  "polygonData": "Polygon data:",
  "import": "Import",
  "importNest": "Import as nest",
  "exportPolygonPoints": "Export Polygon Points (CSV)",
  "gyms": "Gyms:",
  "pokestops": "Pokestops:",
  "spawnpoints": "Spawnpoints:",
  "pokemon": "Pokémon",
  "getOwnLocation": "Get to my location!",
  "coordTypeUnsorted": "unsorted",
  "coordTypeSorted": "auto-sorted",
  "countCircles": "Nombre de cercles:"
}
var frPokemon = ["Bulbizarre","Herbizarre","Florizarre","Salamèche","Reptincel","Dracaufeu","Carapuce","Carabaffe","Tortank","Chenipan","Chrysacier","Papilusion","Aspicot","Coconfort","Dardargnan","Roucool","Roucoups","Roucarnage","Rattata","Rattatac","Piafabec","Rapasdepic","Abo","Arbok","Pikachu","Raichu","Sabelette","Sablaireau","Nidoran♀","Nidorina","Nidoqueen","Nidoran♂","Nidorino","Nidoking","Mélofée","Mélodelfe","Goupix","Feunard","Rondoudou","Grodoudou","Nosferapti","Nosferalto","Mystherbe","Ortide","Rafflésia","Paras","Parasect","Mimitoss","Aéromite","Taupiqueur","Triopikeur","Miaouss","Persian","Psykokwak","Akwakwak","Férosinge","Colossinge","Caninos","Arcanin","Ptitard","Têtarte","Tartard","Abra","Kadabra","Alakazam","Machoc","Machopeur","Mackogneur","Chétiflor","Boustiflor","Empiflor","Tentacool","Tentacruel","Racaillou","Gravalanch","Grolem","Ponyta","Galopa","Ramoloss","Flagadoss","Magnéti","Magnéton","Canarticho","Doduo","Dodrio","Otaria","Lamantine","Tadmorv","Grotadmorv","Kokiyas","Crustabri","Fantominus","Spectrum","Ectoplasma","Onix","Soporifik","Hypnomade","Krabby","Krabboss","Voltorbe","Électrode","Nœunœuf","Noadkoko","Osselait","Ossatueur","Kicklee","Tygnon","Excelangue","Smogo","Smogogo","Rhinocorne","Rhinoféros","Leveinard","Saquedeneu","Kangourex","Hypotrempe","Hypocéan","Poissirène","Poissoroy","Stari","Staross","M. Mime","Insécateur","Lippoutou","Élektek","Magmar","Scarabrute","Tauros","Magicarpe","Léviator","Lokhlass","Métamorph","Évoli","Aquali","Voltali","Pyroli","Porygon","Amonita","Amonistar","Kabuto","Kabutops","Ptéra","Ronflex","Artikodin","Électhor","Sulfura","Minidraco","Draco","Dracolosse","Mewtwo","Mew","Germignon","Macronium","Méganium","Héricendre","Feurisson","Typhlosion","Kaiminus","Crocrodil","Aligatueur","Fouinette","Fouinar","Hoothoot","Noarfang","Coxy","Coxyclaque","Mimigal","Migalos","Nostenfer","Loupio","Lanturn","Pichu","Mélo","Toudoudou","Togepi","Togetic","Natu","Xatu","Wattouat","Lainergie","Pharamp","Joliflor","Marill","Azumarill","Simularbre","Tarpaud","Granivol","Floravol","Cotovol","Capumain","Tournegrin","Héliatronc","Yanma","Axoloto","Maraiste","Mentali","Noctali","Cornèbre","Roigada","Feuforêve","Zarbi","Qulbutoké","Girafarig","Pomdepik","Foretress","Insolourdo","Scorplane","Steelix","Snubbull","Granbull","Qwilfish","Cizayox","Caratroc","Scarhino","Farfuret","Teddiursa","Ursaring","Limagma","Volcaropod","Marcacrin","Cochignon","Corayon","Rémoraid","Octillery","Cadoizo","Démanta","Airmure","Malosse","Démolosse","Hyporoi","Phanpy","Donphan","Porygon2","Cerfrousse","Queulorior","Debugant","Kapoera","Lippouti","Élekid","Magby","Écrémeuh","Leuphorie","Raikou","Entei","Suicune","Embrylex","Ymphect","Tyranocif","Lugia","Ho-Oh","Celebi","Arcko","Massko","Jungko","Poussifeu","Galifeu","Braségali","Gobou","Flobio","Laggron","Medhyèna","Grahyèna","Zigzaton","Linéon","Chenipotte","Armulys","Charmillon","Blindalys","Papinox","Nénupiot","Lombre","Ludicolo","Grainipiot","Pifeuil","Tengalice","Nirondelle","Hélédelle","Goélise","Bekipan","Tarsal","Kirlia","Gardevoir","Arakdo","Maskadra","Balignon","Chapignon","Parécool","Vigoroth","Monaflèmit","Ningale","Ninjask","Munja","Chuchmur","Ramboum","Brouhabam","Makuhita","Hariyama","Azurill","Tarinor","Skitty","Delcatty","Ténéfix","Mysdibule","Galekid","Galegon","Galeking","Méditikka","Charmina","Dynavolt","Élecsprint","Posipi","Négapi","Muciole","Lumivole","Rosélia","Gloupti","Avaltout","Carvanha","Sharpedo","Wailmer","Wailord","Chamallot","Camérupt","Chartor","Spoink","Groret","Spinda","Kraknoix","Vibraninf","Libégon","Cacnea","Cacturne","Tylton","Altaria","Mangriff","Séviper","Séléroc","Solaroc","Barloche","Barbicha","Écrapince","Colhomard","Balbuto","Kaorine","Lilia","Vacilys","Anorith","Armaldo","Barpau","Milobellus","Morphéo","Kecleon","Polichombr","Branette","Skelénox","Téraclope","Tropius","Éoko","Absol","Okéoké","Stalgamin","Oniglali","Obalie","Phogleur","Kaimorse","Coquiperl","Serpang","Rosabyss","Relicanth","Lovdisc","Draby","Drackhaus","Drattak","Terhal","Métang","Métalosse","Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys","Tortipouss","Boskara","Torterra","Ouisticram","Chimpenfeu","Simiabraz","Tiplouf","Prinplouf","Pingoléon","Étourmi","Étourvol","Étouraptor","Keunotor","Castorno","Crikzik","Mélokrik","Lixy","Luxio","Luxray","Rozbouton","Roserade","Kranidos","Charkos","Dinoclier","Bastiodon","Cheniti","Cheniselle","Papilord","Apitrini","Apireine","Pachirisu","Mustébouée","Mustéflott","Ceribou","Ceriflor","Sancoki","Tritosor","Capidextre","Baudrive","Grodrive","Laporeille","Lockpin","Magirêve","Corboss","Chaglam","Chaffreux","Korillon","Moufouette","Moufflair","Archéomire","Archéodong","Manzaï","Mime Jr.","Ptiravi","Pijako","Spiritomb","Griknot","Carmache","Carchacrok","Goinfrex","Riolu","Lucario","Hippopotas","Hippodocus","Rapion","Drascore","Cradopaud","Coatox","Vortente","Écayon","Luminéon","Babimanta","Blizzi","Blizzaroi","Dimoret","Magnézone","Coudlangue","Rhinastoc","Bouldeneu","Élekable","Maganon","Togekiss","Yanmega","Phyllali","Givrali","Scorvol","Mammochon","Porygon-Z","Gallame","Tarinorme","Noctunoir","Momartik","Motisma","Créhelf","Créfollet","Créfadet","Dialga","Palkia","Heatran","Regigigas","Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus","Victini","Vipélierre","Lianaja","Majaspic","Gruikui","Grotichon","Roitiflam","Moustillon","Mateloutre","Clamiral","Ratentif","Miradar","Ponchiot","Ponchien","Mastouffe","Chacripan","Léopardus","Feuillajou","Feuiloutan","Flamajou","Flamoutan","Flotajou","Flotoutan","Munna","Mushana","Poichigeon","Colombeau","Déflaisan","Zébibron","Zéblitz","Nodulithe","Géolithe","Gigalithe","Chovsourir","Rhinolove","Rototaupe","Minotaupe","Nanméouïe","Charpenti","Ouvrifier","Bétochef","Tritonde","Batracné","Crapustule","Judokrak","Karaclée","Larveyette","Couverdure","Manternel","Venipatte","Scobolide","Brutapode","Doudouvet","Farfaduvet","Chlorobule","Fragilady","Bargantua","Mascaïman","Escroco","Crocorible","Darumarond","Darumacho","Maracachi","Crabicoque","Crabaraque","Baggiguane","Baggaïd","Cryptéro","Tutafeh","Tutankafer","Carapagos","Mégapagos","Arkéapti","Aéroptéryx","Miamiasme","Miasmax","Zorua","Zoroark","Chinchidou","Pashmilla","Scrutella","Mesmérella","Sidérella","Nucléos","Méios","Symbios","Couaneton","Lakmécygne","Sorbébé","Sorboul","Sorbouboul","Vivaldaim","Haydaim","Emolga","Carabing","Lançargot","Trompignon","Gaulet","Viskuse","Moyade","Mamanbo","Statitik","Mygavolt","Grindur","Noacier","Tic","Clic","Cliticlic","Anchwatt","Lampéroie","Ohmassacre","Lewsor","Neitram","Funécire","Mélancolux","Lugulabre","Coupenotte","Incisache","Tranchodon","Polarhume","Polagriffe","Hexagel","Escargaume","Limaspeed","Limonde","Kungfouine","Shaofouine","Drakkarmin","Gringolem","Golemastoc","Scalpion","Scalproie","Frison","Furaiglon","Gueriaigle","Vostourno","Vaututrice","Aflamanoir","Fermite","Solochi","Diamat","Trioxhydre","Pyronille","Pyrax","Cobaltium","Terrakium","Viridium","Boréas","Fulguris","Reshiram","Zekrom","Démétéros","Kyurem","Keldeo","Meloetta","Genesect","Marisson","Boguérisse","Blindépique","Feunnec","Roussil","Goupelin","Grenousse","Croâporal","Amphinobi","Sapereau","Excavarenne","Passerouge","Braisillon","Flambusard","Lépidonille","Pérégrain","Prismillon","Hélionceau","Némélios","Flabébé","Floette","Florges","Cabriolaine","Chevroum","Pandespiègle","Pandarbare","Couafarel","Psystigri","Mistigrix","Monorpale","Dimoclès","Exagide","Fluvetin","Cocotine","Sucroquin","Cupcanaille","Sepiatop","Sepiatroce","Opermine","Golgopathe","Venalgue","Kravarech","Flingouste","Gamblast","Galvaran","Iguolta","Ptyranidur","Rexillius","Amagara","Dragmara","Nymphali","Brutalibré","Dedenne","Strassie","Mucuscule","Colimucus","Muplodocus","Trousselin","Brocélôme","Desséliande","Pitrouille","Banshitrouye","Grelaçon","Séracrawl","Sonistrelle","Bruyverne","Xerneas","Yveltal","Zygarde","Diancie","Hoopa","Volcanion","Brindibou","Efflèche","Archéduc","Flamiaou","Matoufeu","Félinferno","Otaquin","Otarlette","Oratoria","Picassaut","Piclairon","Bazoucan","Manglouton","Argouste","Larvibule","Chrysapile","Lucanon","Crabagarre","Crabominable","Plumeline","Bombydou","Rubombelle","Rocabot","Lougaroc","Froussardine","Vorastérie","Prédastérie","Tiboudet","Bourrinos","Araqua","Tarenbulle","Mimantis","Floramantis","Spododo","Lampignon","Tritox","Malamandre","Nounourson","Chelours","Croquine","Candine","Sucreine","Guérilande","Gouroutan","Quartermac","Sovkipou","Sarmuraï","Bacabouh","Trépassable","Concombaffe","Type:0","Silvallié","Météno","Dodoala","Boumata","Togedemaru","Mimiqui","Denticrisse","Draïeul","Sinistrail","Bébécaille","Écaïd","Ékaïser","Tokorico","Tokotoro","Tokopiyon","Tokopisco","Cosmog","Cosmovum","Solgaleo","Lunala","Zéroïd","Mouscoto","Cancrelove","Câblifère","Bamboiselle","Katagami","Engloutyran","Necrozma","Magearna","Marshadow","Vémini","Mandrillon","Ama-Ama","Pierroteknik","Zeraora"];